import type { AppProps } from 'next/app';
import Head from 'next/head';
import Link from 'next/link';
import 'styles/globals.css';
import { ProjectProvider } from 'components/ProjectProvider';
import styles from 'styles/Home.module.css';
import { Navi } from 'components/Navi/Navi';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ProjectProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <nav>
            <Navi />
          </nav>
        </header>
        <main className={styles.content}>
          <Component {...pageProps} />
        </main>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by nx
        </a>
      </footer>
    </ProjectProvider>
  );
}
export default MyApp;
